### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/uncledane-web#37]
# UT Donations

General overview/discussion of how the donation system will be implemented.

### Donation progress bar
- Generic 0-100% or an actual dollar amount?

### Per-region donation totals
- To gamify regions to out-donate eachother
- Select a server you want to tag your donations to when creating them, or a general "all" option for no preference.
- Some type of non-monetary "prize" they can claim? 
  - Trophy on the server browser?

### Payment processor / methods
- Stripe
- Paypal?
- Crypto?
- Linden Dollars?
- Save The Kids coin?

### "Rewards" / "Perks"
- Uncledane (or maybe some other yters too?) craft hats
- Zero in-game rewards at all, no pay2win or anything that could be perceived as p2w.
- Discord donator role?
- Discord announcement of new donations, or possibly just monthly donator stats?
- Top donators per month/year/total
- `Uncle Dane — Today at 15:56 Oh yeah? Implement a sound clip of earthworm jim saying "groovy!" when u click donate`

**Comment by UncleDane** [comment]
I think the donation progress bar can feature the percentage prominently, with the actual dollar amount total (rounded up to the nearest hundredth) as a subtitle would be good.

I like the idea of gamifying the donation goal each month based on region. And I think the highest donating region from last month should get some kind of badge applied to it to signify their status as "Uncle's Favorite Of The Month" or something like that. (You can mouse over the badge/gold ribbon/gold star to see the official title).

Beneath the donation progress bar, there could be a TOP 10 DONATORS of the month list to give specific high rollers a shoutout (with a custom message attached, if approved by moderation). People who set up a recurring payment can ensure they remain on the list every month this way.

Payment processor should be covered pretty effectively by just Stripe and Paypal.

The main non-monetary reward I would be good with giving out would be a Discord donator role, however there would be too prerequisites to enabling that. 
---- First off, I will likely be setting up a Discord server specifically for Uncletopia, so that everything to do with the server, as well as the maintaining of the server can be consolidated onto its own thing, and not continue to clutter up the Uncle Dane Community Discord as we expand (plus, there are likely many regular players who aren't interested in me or my content, but still want to keep up to date with Uncletopia). The "Uncletopia Discord" is where I would award donators with a special role.
---- Secondly, I would like this role to be awarded automatically using a bot or something. It will be too difficult to expect moderators to confirm donator Discord accounts and manually award the role to them. So if that is possible to set up, then I am totally on board with that donation perk.

And finally, yes I believe that Earthworm Jim saying "Groovy!" is essential to the interactive nature of the donation button. Please refer to [this video](https://www.youtube.com/watch?v=juHgQBB2tLU) for reference.
