### ISSUE TITLE
Migrate to react

### ISSUE THREAD

**Issue by leighmacdonald** [leighmacdonald/uncledane-web#41]
Migrate to react since we are going to be doing more dynamic stuff anyways.

Also drops Zurb CSS framework in favour of material-ui

**Comment by Naleksuh** [comment]
@leighmacdonald React is a frontend language used mainly for interactive things like games and chat. React for entire webpages is a strongly discouraged practice because it will load pages measurably slower, there is no browser compatibility, and it will be impossible to use the website without JavaScript (see https://github.com/leighmacdonald/uncletopia-web/issues/1). This is without changing the experience as it would be for returning actual HTML pages but with more inconvenience to the end user. **Please do not!**

**Comment by leighmacdonald** [comment]
The scope of this has completely changed and its not going to happen on here at all. The site will largely remain as-is.
